### ISSUE TITLE
there is error in log 

### ISSUE THREAD

**Issue by XuhaoZhao** [agentic-labs/lsproxy#108]
when i run lsproxy in docker to start my java project without network，it looks there is some error in jdtls log, i want fix this error ，so i add initialize param，but i did't work. even i read the source code of jdtls and vscode-java.i think the parm is ok. so i want to know why the param doesn't work

    async fn get_initialize_params(&mut self, root_path: String) -> InitializeParams {
    let settings = serde_json::json!({
        "settings": {
            "java": {
                "import": {
                    "gradle": {
                        "enabled": false
                    }
                }
            }
        }
    });
        let params = InitializeParams {
            capabilities: self.get_capabilities(),
            workspace_folders: Some(
                self.find_workspace_folders(root_path.clone())
                    .await
                    .unwrap(),
            ),
            root_uri: Some(Url::from_file_path(&root_path).unwrap()),
            initialization_options: Some(settings),
            ..Default::default()
        };
        debug!("Generated InitializeParams: {:?}", serde_json::to_value(&params).unwrap());
        params
    }

!SESSION 2024-12-31 05:08:26.248 -----------------------------------------------
eclipse.buildId=unknown
java.version=17.0.13
java.vendor=Debian
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Command-line arguments:  -data /usr/src/app/jdtls_workspace

!ENTRY org.eclipse.jdt.ls.core 1 0 2024-12-31 05:08:28.506
!MESSAGE class org.eclipse.jdt.ls.core.internal.JavaLanguageServerPlugin is started

!ENTRY org.eclipse.jdt.ls.core 1 0 2024-12-31 05:08:28.694
!MESSAGE Main thread is waiting

!ENTRY org.eclipse.jdt.ls.core 1 0 2024-12-31 05:08:28.715
!MESSAGE >> initialize

!ENTRY org.eclipse.jdt.ls.core 1 0 2024-12-31 05:08:28.718
!MESSAGE Initializing Java Language Server 1.44.0.202412301758

!ENTRY org.eclipse.jdt.ls.core 1 0 2024-12-31 05:08:28.719
!MESSAGE Started org.eclipse.m2e.core 1ms

!ENTRY org.eclipse.jdt.ls.core 1 0 2024-12-31 05:08:29.542
!MESSAGE ProjectRegistryRefreshJob finished 823ms

!ENTRY org.eclipse.jdt.ls.core 1 0 2024-12-31 05:08:29.561
!MESSAGE Started org.eclipse.buildship.core 18ms

!ENTRY org.eclipse.jdt.ls.core 1 0 2024-12-31 05:08:29.628
!MESSAGE Static Commands: []

!ENTRY org.eclipse.jdt.ls.core 1 0 2024-12-31 05:08:29.629
!MESSAGE Non-Static Commands: [java.project.import, java.project.changeImportedProjects, java.navigate.openTypeHierarchy, java.project.resolveStackTraceLocation, java.edit.handlePasteEvent, java.edit.stringFormatting, java.project.getSettings, java.project.resolveWorkspaceSymbol, java.project.upgradeGradle, java.project.createModuleInfo, java.vm.getAllInstalls, java.edit.organizeImports, java.project.refreshDiagnostics, java.project.removeFromSourcePath, java.project.listSourcePaths, java.project.updateSettings, java.project.getAll, java.reloadBundles, java.project.isTestFile, java.project.resolveText, java.project.getClasspaths, java.navigate.resolveTypeHierarchy, java.edit.smartSemicolonDetection, java.project.updateSourceAttachment, java.project.updateClassPaths, java.decompile, java.protobuf.generateSources, java.project.resolveSourceAttachment, java.project.updateJdk, java.project.addToSourcePath, java.completion.onDidSelect]

!ENTRY org.eclipse.jdt.ls.core 1 0 2024-12-31 05:08:29.639
!MESSAGE RepositoryRegistryUpdateJob finished 0ms

!ENTRY org.eclipse.jdt.ls.core 1 0 2024-12-31 05:08:29.648
!MESSAGE >> initialized

!ENTRY org.eclipse.jdt.ls.core 1 0 2024-12-31 05:08:29.667
!MESSAGE Importing Maven project(s)

!ENTRY org.eclipse.buildship.core 2 0 2024-12-31 05:08:40.230
!MESSAGE Could not load Gradle version information
!STACK 0
org.gradle.api.UncheckedIOException: Cannot download published Gradle versions.
        at org.eclipse.buildship.core.internal.util.gradle.PublishedGradleVersions.downloadVersionInformation(PublishedGradleVersions.java:167)
        at org.eclipse.buildship.core.internal.util.gradle.PublishedGradleVersions.tryToDownloadAndCacheVersions(PublishedGradleVersions.java:151)
        at org.eclipse.buildship.core.internal.util.gradle.PublishedGradleVersions.create(PublishedGradleVersions.java:111)
        at org.eclipse.buildship.core.internal.util.gradle.PublishedGradleVersionsWrapper$LoadVersionsJob.run(PublishedGradleVersionsWrapper.java:73)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.net.SocketTimeoutException: Read timed out
        at java.base/sun.nio.ch.NioSocketImpl.timedRead(NioSocketImpl.java:288)
        at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:314)
        at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:355)
        at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:808)
        at java.base/java.net.Socket$SocketInputStream.read(Socket.java:966)
        at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:484)
        at java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:478)
        at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:160)
        at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:111)
        at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1510)
        at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1425)
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:455)
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:426)
        at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:589)
        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:187)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1701)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1625)
        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
        at org.eclipse.buildship.core.internal.util.gradle.PublishedGradleVersions.downloadVersionInformation(PublishedGradleVersions.java:164)
        ... 4 more

!ENTRY org.eclipse.jdt.ls.core 1 0 2024-12-31 05:09:02.539
!MESSAGE Workspace initialized in 32901ms

!ENTRY org.eclipse.jdt.ls.core 1 0 2024-12-31 05:09:02.547
!MESSAGE >> initialization job finished

!ENTRY org.eclipse.jdt.ls.core 1 0 2024-12-31 05:09:04.215
!MESSAGE >> build jobs finished

!ENTRY org.eclipse.jdt.ls.core 1 0 2024-12-31 05:09:04.215
!MESSAGE >> registerWatchers'

**Comment by maks-ivanov** [comment]
```
let settings = serde_json::json!({
    "settings": {
        "java": {
            "import": {
                "gradle": {
                    "enabled": false
                }
            }
        }
    }
});
```
this looks correct. Have you tried `offline: {enabled: true}` and/or `autobuild: {enabled: false}`

**Comment by maks-ivanov** [comment]
major fixes went out for java, this may be fixed now
